### ISSUE TITLE
Disallow usage with unsupported shells

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/shescape#139]
[The documentation currently lists supported shells and recommends not using `shescape` with any other shells](https://github.com/ericcornelissen/shescape/blob/f2ab42d6f974d1c43bb3e9450483eda5ec5ee852/README.md#shells). However, this is easy to miss and moreover a developer may not realize they're using an unsupported shell. To ensure `shescape` isn't used ineffectively, the API should be changed such that using `shescape` with an unsupported shell fails hard.

> :warning: This change would be a breaking change and require a major version bump!

~~This change should probably not be released before #156 is resolved.~~

## Proposal

All `shescape` function should be updated such that they throw an error when invoked in way that it will be used with an unsupported shell. In other words, [the documentation](https://github.com/ericcornelissen/shescape/blob/8e0d66f7d69d12c96dce8fc9c539b7d9390dc425/index.js#L20-L32) (and accordingly implementation) should be changed following:

```diff
  * @throws {TypeError} One of the arguments is not stringable.
+ * @throws {Error} Shell is not supported.
```

To still enable anyone to use `shescape` with an "unsupported" shell - where unsupported may mean anything from untested to not-correctly detected - something like a separate function should be available that functions exactly like the original except that it doesn't throw an error for unsupported shells. This should look something like the following to clearly communicate the potential implications of using the function:

```js
const arg = quote_UNSAFE("; ls -al");
```

## Scope

In scope for this ticket is:

- [x] When the `shell` is detected but not supported. (#963)
- [x] When the location of configured `shell` could not be determined ([ref](https://github.com/ericcornelissen/shescape/blob/cf0a910e82bff1afec300416c756f3ddb8c7efa3/src/executables.js#L30-L31)). (#963)
- [x] When _Shescape_ fails to find the executable for `shell` on disk ([ref](https://github.com/ericcornelissen/shescape/blob/cf0a910e82bff1afec300416c756f3ddb8c7efa3/src/executables.js#L36-L37)). (#963)

**Comment by ericcornelissen** [comment]
RE:

> To still enable anyone to use shescape with an "unsupported" shell - where unsupported may mean anything from untested to not-correctly detected - something like a separate function should be available that functions exactly like the original except that it doesn't throw an error for unsupported shells.

With #1067 it was chosen to not include such an option as there's a reasonable alternative available: using no shell.
