### ISSUE TITLE
Structural changes to the documentation for improved clarity

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/shescape#160]
# Documentation

- **Shescape version**: `1.4.0`
- **Operating system**: _any_
- **Shell**: _any_

## Description

This issue is a place for me to collect my thoughts and ideas regarding the documentation with an eye to improving the documentation for "usability".

If you have any suggestions w.r.t. the structure of the documentation, please leave a comment or open [a new issue](https://github.com/ericcornelissen/shescape/issues/new?assignees=&labels=documentation&template=documentation.md). If you have more specific suggestions for the documentation, please open [a new issue](https://github.com/ericcornelissen/shescape/issues/new?assignees=&labels=documentation&template=documentation.md).

> **Note**: While this issue is part of the `2.0.0` milestone, any of these changes may be applied to the documentation for `v1.x.x` as well. The intend is simply to close this out prior to/along with the release of `2.0.0`.

## Ideas

- [x] The **Recipes** section (#274)
  - Take the [current content of the **Recipes** section](https://github.com/ericcornelissen/shescape/tree/b486a5f02c270a0a1840750235aa386b97946037#recipes) and put it in a section on "Usage with `child_process`" that outlines how to use Shescape with each of the functions provided by the [`child_process`](https://nodejs.org/api/child_process.html) package. This would allow for a convenient way to add recipes with other process spawners.
- [x] The **Input-Output** subsections. (#612)
- [x] Provide examples (dos) and don'ts in the JSDoc for each function exposed by Shescape. (#610)
- [ ] Document writing guidelines in [the Contributing Guidelines](https://github.com/ericcornelissen/shescape/blob/7a4fa93db29f5e19a23ecf9cfb802fc69dbbf7bf/CONTRIBUTING.md#package-documentation) (#652)
