### ISSUE TITLE
Use `node:` protocol for importing builtin modules

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/shescape#237]
# Enhancement

## Description

Update all the code to use [`node:` imports](https://nodejs.org/api/esm.html#node-imports) for all builtin modules (e.g. `fs` or `path`).

Considering the version history of `node:` imports (from [1](https://nodejs.org/api/esm.html#node-imports)):

| Version                | Changes                                        |
| ---------------------: | :--------------------------------------------- |
|  `v14.18.0`, `v16.0.0` | Added `node:` import support to `require(...)` |
| `v14.13.1`, `v12.20.0` | Added in: `v14.13.1`, `v12.20.0`               |

Partial support (only with `import x from "y"`) for it was added in later v12 and v14 releases and full support is only present since later v14 releases and all releases since v16. This means:

1. ~~The [scripts](https://github.com/ericcornelissen/shescape/tree/main/script) and [tests](https://github.com/ericcornelissen/shescape/tree/main/test) can be updated immediately given that the development Node.js version is (currently) v16.13.1 ([2](https://github.com/ericcornelissen/shescape/blob/ac059a078b3aaec41910e07dc649212b3476c011/.nvmrc)).~~
2. The source code ([`index.js`](https://github.com/ericcornelissen/shescape/blob/main/index.js) and the contents of [src](https://github.com/ericcornelissen/shescape/tree/main/src)) **CANNOT** be updated yet. First and foremost, v1 of Shescape needs to stay backwards compatible with `>=10.13.0` ([3](https://github.com/ericcornelissen/shescape/blob/ac059a078b3aaec41910e07dc649212b3476c011/package.json#L67)).
   Second, with this project I aim to support as many LTS Node.js releases [^1]. At the time of writing, the latest LTS is v12 (for a couple more days) so to be able to support all LTS releases, `node:` imports cannot yet be used. In fact, not until v16 is the latest LTS can the `node:` protocol be used in Shescape's source code.

## Progress

- [x] Use `node:` imports in scripts (#240)
- [x] Use `node:` imports in tests (#240)
- [ ] Use `node:` imports in source code (#963)

---

Relates to: [#193](https://github.com/ericcornelissen/shescape/issues/193)

[^1]: By "an LTS release" I mean any version in that is part of a LTS major version. So if v14 is an LTS release, v14.0.0 and all v14 releases are "an LTS release".

**Comment by ericcornelissen** [comment]
This was first available in [2.0.0-rc1](https://www.npmjs.com/package/shescape/v/2.0.0-rc1).
