### ISSUE TITLE
Management of non-package registry dependencies

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/shescape#583]
Many of this project's runtime and development dependencies are explicitly tracked (in [`package-lock.json`](https://github.com/ericcornelissen/shescape/blob/8130e9c799705930f9fbd9ce6c18b2c6d16a6156/package-lock.json) or [GitHub Actions workflows](https://github.com/ericcornelissen/shescape/tree/8130e9c799705930f9fbd9ce6c18b2c6d16a6156/.github/workflows)), some system-level development dependencies aren't explicitly tracked but this is considered fine[^1] (git, Node.js, npm, Docker, EditorConfig), but some development dependencies aren't explicitly tracked and/or kept up-to-date but ideally are. This issue is about that last category.

> **Note**: Feel free to comment on this issue if you think this list is incomplete or if you have any suggestions for improvements.

### Overview

- [x] [actionlint](https://github.com/ericcornelissen/shescape/blob/8130e9c799705930f9fbd9ce6c18b2c6d16a6156/CONTRIBUTING.md?plain=1#L103): ~~ideally tracked & kept up-to-date.~~
  - Tracking added in #589
  - Updating added in #613
- [x] CI workflow images: ideally pinned to help with reproducibility. See #576.
- [x] [ShellCheck](https://github.com/ericcornelissen/shescape/blob/8130e9c799705930f9fbd9ce6c18b2c6d16a6156/CONTRIBUTING.md?plain=1#L104): ~~ideally tracked & kept up-to-date~~.
  - Tracking added in #589
  - Updating added in #613

[^1]: If known, these should have a minimum required version specified to make contributing easier
